-- B-05-02 durable-summary fix: persist each agent's validated output JSON so a
-- cache hit can restore the REAL result with $0 API calls.
--
-- Before this column, agent_runs stored only metadata (tokens, cost, status).
-- When a run committed its agent_runs rows but the vault git push did not land
-- (e.g. the 10-minute Actions timeout cancelled the job after the DB commit but
-- before "Commit synthesized wiki"), a subsequent re-run hit the cache and the
-- B-05-02 recovery path could not recover the summary text — it fell back to the
-- "(summary unavailable — cached run)" placeholder. Storing output_json lets the
-- recovery path reconstruct the real SummarizerOutput (and every other agent
-- output) from cache, so a real summary always lands on retry without re-calling
-- the API.
--
-- output_json holds the JSON serialization of the validated pydantic output
-- (model_dump_json()) for status='ok' rows; NULL for error rows and for legacy
-- rows written before this migration (the recovery path treats NULL as
-- "no cached output" and preserves the prior RuntimeError-on-cache-hit behavior).
--
-- SQLite has no `ADD COLUMN IF NOT EXISTS`; _run_migrations() in registry.py
-- swallows the "duplicate column name" error so this stays idempotent on every
-- connect.
ALTER TABLE agent_runs ADD COLUMN output_json TEXT;
